package com.shmcc.webservicedemo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-15T11:18:59.218+08:00
 * Generated source version: 3.1.16
 * 
 */
@WebServiceClient(name = "AppService", 
                  wsdlLocation = "file:/C:/Users/john/AppData/Local/Temp/tempdir7467035380586725310.tmp/yc_1.wsdl",
                  targetNamespace = "http://webserviceDemo.shmcc.com/") 
public class AppService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webserviceDemo.shmcc.com/", "AppService");
    public final static QName AppServiceImplPort = new QName("http://webserviceDemo.shmcc.com/", "AppServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/john/AppData/Local/Temp/tempdir7467035380586725310.tmp/yc_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AppService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/john/AppData/Local/Temp/tempdir7467035380586725310.tmp/yc_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AppService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AppService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AppService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AppService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServiceImplPort")
    public AppService getAppServiceImplPort() {
        return super.getPort(AppServiceImplPort, AppService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppService
     */
    @WebEndpoint(name = "AppServiceImplPort")
    public AppService getAppServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AppServiceImplPort, AppService.class, features);
    }

}
