
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.shmcc.webservicedemo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.springframework.stereotype.Component;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-15T11:18:59.175+08:00
 * Generated source version: 3.1.16
 * 
 */

@javax.jws.WebService(
                      serviceName = "AppService",
                      portName = "AppServiceImplPort",
                      targetNamespace = "http://webserviceDemo.shmcc.com/",
                      //wsdlLocation = "file:/C:/Users/john/AppData/Local/Temp/tempdir7467035380586725310.tmp/yc_1.wsdl",
                      endpointInterface = "com.shmcc.webservicedemo.AppService")
@Component     
public class AppServiceImplPortImpl implements AppService {

    private static final Logger LOG = Logger.getLogger(AppServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.shmcc.webservicedemo.AppService#process(com.shmcc.webservicedemo.UserInputItem arg0)*
     */
    public com.shmcc.webservicedemo.UserOutputDomain process(com.shmcc.webservicedemo.UserInputItem arg0) throws UnsupportedEncodingException_Exception   { 
        LOG.info("Executing operation process");
        System.out.println(arg0);
        try {
            com.shmcc.webservicedemo.UserOutputDomain _return = new UserOutputDomain();
            _return.setId(new Long(23333));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UnsupportedEncodingException_Exception("UnsupportedEncodingException...");
    }

}
