
package com.shmcc.webservicedemo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-07-15T11:18:59.155+08:00
 * Generated source version: 3.1.16
 */

@WebFault(name = "UnsupportedEncodingException", targetNamespace = "http://webserviceDemo.shmcc.com")
public class UnsupportedEncodingException_Exception extends Exception {
    
    private com.shmcc.webservicedemo.UnsupportedEncodingException unsupportedEncodingException;

    public UnsupportedEncodingException_Exception() {
        super();
    }
    
    public UnsupportedEncodingException_Exception(String message) {
        super(message);
    }
    
    public UnsupportedEncodingException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnsupportedEncodingException_Exception(String message, com.shmcc.webservicedemo.UnsupportedEncodingException unsupportedEncodingException) {
        super(message);
        this.unsupportedEncodingException = unsupportedEncodingException;
    }

    public UnsupportedEncodingException_Exception(String message, com.shmcc.webservicedemo.UnsupportedEncodingException unsupportedEncodingException, java.lang.Throwable cause) {
        super(message, cause);
        this.unsupportedEncodingException = unsupportedEncodingException;
    }

    public com.shmcc.webservicedemo.UnsupportedEncodingException getFaultInfo() {
        return this.unsupportedEncodingException;
    }
}
